### PR TITLE
Add relevant meta for better client rendering

### PR DESCRIPTION
**Pull request by debo**
More info about the X-UA-Compatible meta can be found [here](http://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do#6771584)

I'll let you decide whether you want to use it or not.

### CODE REVIEW

**Comment by cdesewell** [comment]
Please write unit test

**Comment by debo** [comment]
Sure if you can show me how or point me in the right direction, I am quite new to frontend development

**Comment by cdesewell** [comment]
this is a mono repo, everything you need can be found here

**Comment by debo** [comment]
I had a look but couldn't find any tests folder in the project. Am I missing something?

**Comment by cdesewell** [comment]
yes

**Comment by debo** [comment]
Man you are not listening to me, I can't unit test that code, also unit tests are useless a friend of a friend of mine who works at Tesla said so. It's better if we deploy it and we test it live manually. That's how the new cool kids do it.

**Pull request merged**
